UPDATE mob_db SET kName = "Scorpion" WHERE ID = 1001;
UPDATE mob_db SET kName = "Poring" WHERE ID = 1002;
UPDATE mob_db SET kName = "Frelon" WHERE ID = 1004;
UPDATE mob_db SET kName = "Familier" WHERE ID = 1005;
UPDATE mob_db SET kName = "Fabre" WHERE ID = 1007;
UPDATE mob_db SET kName = "Chrysalide" WHERE ID = 1008;
UPDATE mob_db SET kName = "Condor" WHERE ID = 1009;
UPDATE mob_db SET kName = "Saule" WHERE ID = 1010;
UPDATE mob_db SET kName = "Chonchon" WHERE ID = 1011;
UPDATE mob_db SET kName = "Grenouille Roda" WHERE ID = 1012;
UPDATE mob_db SET kName = "Loup" WHERE ID = 1013;
UPDATE mob_db SET kName = "Spore" WHERE ID = 1014;
UPDATE mob_db SET kName = "Zombie" WHERE ID = 1015;
UPDATE mob_db SET kName = "Squelette Archer" WHERE ID = 1016;
UPDATE mob_db SET kName = "Crémeux" WHERE ID = 1018;
UPDATE mob_db SET kName = "Péco Péco" WHERE ID = 1019;
UPDATE mob_db SET kName = "Mandragore" WHERE ID = 1020;
UPDATE mob_db SET kName = "Guerrier Orc" WHERE ID = 1023;
UPDATE mob_db SET kName = "Queue-de-Rat" WHERE ID = 1024;
UPDATE mob_db SET kName = "Boa" WHERE ID = 1025;
UPDATE mob_db SET kName = "Munak" WHERE ID = 1026;
UPDATE mob_db SET kName = "Squelette Soldat" WHERE ID = 1028;
UPDATE mob_db SET kName = "Isis" WHERE ID = 1029;
UPDATE mob_db SET kName = "Anaconda" WHERE ID = 1030;
UPDATE mob_db SET kName = "Poporing" WHERE ID = 1031;
UPDATE mob_db SET kName = "Vérit" WHERE ID = 1032;
UPDATE mob_db SET kName = "Saule Ancien" WHERE ID = 1033;
UPDATE mob_db SET kName = "Grenouille Thara" WHERE ID = 1034;
UPDATE mob_db SET kName = "Mouche Guerrière" WHERE ID = 1035;
UPDATE mob_db SET kName = "Goule" WHERE ID = 1036;
UPDATE mob_db SET kName = "Vipère" WHERE ID = 1037;
UPDATE mob_db SET kName = "Osiris" WHERE ID = 1038;
UPDATE mob_db SET kName = "Baphomet" WHERE ID = 1039;
UPDATE mob_db SET kName = "Golem" WHERE ID = 1040;
UPDATE mob_db SET kName = "Momie" WHERE ID = 1041;
UPDATE mob_db SET kName = "Chonchon d'Acier" WHERE ID = 1042;
UPDATE mob_db SET kName = "Obeaune" WHERE ID = 1044;
UPDATE mob_db SET kName = "Marc" WHERE ID = 1045;
UPDATE mob_db SET kName = "Doppelganger" WHERE ID = 1046;
UPDATE mob_db SET kName = "Oeuf de Péco Péco" WHERE ID = 1047;
UPDATE mob_db SET kName = "Oeuf de Chapardeur" WHERE ID = 1048;
UPDATE mob_db SET kName = "Picky" WHERE ID = 1049;
UPDATE mob_db SET kName = "Picky" WHERE ID = 1050;
UPDATE mob_db SET kName = "Chapardeur" WHERE ID = 1051;
UPDATE mob_db SET kName = "Rocker" WHERE ID = 1052;
UPDATE mob_db SET kName = "Chapardeuse" WHERE ID = 1053;
UPDATE mob_db SET kName = "Grand Chapardeur" WHERE ID = 1054;
UPDATE mob_db SET kName = "Muka" WHERE ID = 1055;
UPDATE mob_db SET kName = "Fumard" WHERE ID = 1056;
UPDATE mob_db SET kName = "Yoyo" WHERE ID = 1057;
UPDATE mob_db SET kName = "Métalleux" WHERE ID = 1058;
UPDATE mob_db SET kName = "Maîtresse" WHERE ID = 1059;
UPDATE mob_db SET kName = "Yéti" WHERE ID = 1060;
UPDATE mob_db SET kName = "Cauchemar" WHERE ID = 1061;
UPDATE mob_db SET kName = "Poring de Noël" WHERE ID = 1062;
UPDATE mob_db SET kName = "Lunatique" WHERE ID = 1063;
UPDATE mob_db SET kName = "Megalodon" WHERE ID = 1064;
UPDATE mob_db SET kName = "Strouf" WHERE ID = 1065;
UPDATE mob_db SET kName = "Vadon" WHERE ID = 1066;
UPDATE mob_db SET kName = "Cornutus" WHERE ID = 1067;
UPDATE mob_db SET kName = "Hydre" WHERE ID = 1068;
UPDATE mob_db SET kName = "Espadon" WHERE ID = 1069;
UPDATE mob_db SET kName = "Kukre" WHERE ID = 1070;
UPDATE mob_db SET kName = "Squelette Pirate" WHERE ID = 1071;
UPDATE mob_db SET kName = "Kaho" WHERE ID = 1072;
UPDATE mob_db SET kName = "Crabe" WHERE ID = 1073;
UPDATE mob_db SET kName = "Crustacé" WHERE ID = 1074;
UPDATE mob_db SET kName = "Tortue" WHERE ID = 1075;
UPDATE mob_db SET kName = "Squelette" WHERE ID = 1076;
UPDATE mob_db SET kName = "Spore Empoisonnée" WHERE ID = 1077;
UPDATE mob_db SET kName = "Plante Rouge" WHERE ID = 1078;
UPDATE mob_db SET kName = "Plante Bleue" WHERE ID = 1079;
UPDATE mob_db SET kName = "Plante Verte" WHERE ID = 1080;
UPDATE mob_db SET kName = "Plante Jaune" WHERE ID = 1081;
UPDATE mob_db SET kName = "Plante Blanche" WHERE ID = 1082;
UPDATE mob_db SET kName = "Plante Luminescente" WHERE ID = 1083;
UPDATE mob_db SET kName = "Champignon Noir" WHERE ID = 1084;
UPDATE mob_db SET kName = "Champignon Rouge" WHERE ID = 1085;
UPDATE mob_db SET kName = "Chapardeur Doré" WHERE ID = 1086;
UPDATE mob_db SET kName = "Héros des Orcs" WHERE ID = 1087;
UPDATE mob_db SET kName = "Vocal" WHERE ID = 1088;
UPDATE mob_db SET kName = "Crapaud" WHERE ID = 1089;
UPDATE mob_db SET kName = "Mastering" WHERE ID = 1090;
UPDATE mob_db SET kName = "Mouche-Dragon" WHERE ID = 1091;
UPDATE mob_db SET kName = "Loup Errant" WHERE ID = 1092;
UPDATE mob_db SET kName = "Éclipse" WHERE ID = 1093;
UPDATE mob_db SET kName = "Ambernite" WHERE ID = 1094;
UPDATE mob_db SET kName = "André" WHERE ID = 1095;
UPDATE mob_db SET kName = "Angéling" WHERE ID = 1096;
UPDATE mob_db SET kName = "Oeuf de Fourmi" WHERE ID = 1097;
UPDATE mob_db SET kName = "Anubis" WHERE ID = 1098;
UPDATE mob_db SET kName = "Argiope" WHERE ID = 1099;
UPDATE mob_db SET kName = "Argos" WHERE ID = 1100;
UPDATE mob_db SET kName = "Baphomet Jr." WHERE ID = 1101;
UPDATE mob_db SET kName = "Bathory" WHERE ID = 1102;
UPDATE mob_db SET kName = "Caramel" WHERE ID = 1103;
UPDATE mob_db SET kName = "Coco" WHERE ID = 1104;
UPDATE mob_db SET kName = "Deniro" WHERE ID = 1105;
UPDATE mob_db SET kName = "Loup du Désert" WHERE ID = 1106;
UPDATE mob_db SET kName = "Jeune Loup du Désert" WHERE ID = 1107;
UPDATE mob_db SET kName = "Déviace" WHERE ID = 1108;
UPDATE mob_db SET kName = "Deviruchi" WHERE ID = 1109;
UPDATE mob_db SET kName = "Dokebi" WHERE ID = 1110;
UPDATE mob_db SET kName = "Drainlier" WHERE ID = 1111;
UPDATE mob_db SET kName = "Drake" WHERE ID = 1112;
UPDATE mob_db SET kName = "Drops" WHERE ID = 1113;
UPDATE mob_db SET kName = "Cendreux" WHERE ID = 1114;
UPDATE mob_db SET kName = "Eddga" WHERE ID = 1115;
UPDATE mob_db SET kName = "Eggyra" WHERE ID = 1116;
UPDATE mob_db SET kName = "Druide Maléfique" WHERE ID = 1117;
UPDATE mob_db SET kName = "Flora" WHERE ID = 1118;
UPDATE mob_db SET kName = "Frilldora" WHERE ID = 1119;
UPDATE mob_db SET kName = "Ghostring" WHERE ID = 1120;
UPDATE mob_db SET kName = "Fouisseur" WHERE ID = 1121;
UPDATE mob_db SET kName = "Gobelin" WHERE ID = 1122;
UPDATE mob_db SET kName = "Gobelin" WHERE ID = 1123;
UPDATE mob_db SET kName = "Gobelin" WHERE ID = 1124;
UPDATE mob_db SET kName = "Gobelin" WHERE ID = 1125;
UPDATE mob_db SET kName = "Gobelin" WHERE ID = 1126;
UPDATE mob_db SET kName = "Hode" WHERE ID = 1127;
UPDATE mob_db SET kName = "Cornu" WHERE ID = 1128;
UPDATE mob_db SET kName = "Horong" WHERE ID = 1129;
UPDATE mob_db SET kName = "Jack" WHERE ID = 1130;
UPDATE mob_db SET kName = "Joker" WHERE ID = 1131;
UPDATE mob_db SET kName = "Khalitzburg" WHERE ID = 1132;
UPDATE mob_db SET kName = "Kobold" WHERE ID = 1133;
UPDATE mob_db SET kName = "Kobold" WHERE ID = 1134;
UPDATE mob_db SET kName = "Kobold" WHERE ID = 1135;
UPDATE mob_db SET kName = "Magnolia" WHERE ID = 1138;
UPDATE mob_db SET kName = "Mante" WHERE ID = 1139;
UPDATE mob_db SET kName = "Marduk" WHERE ID = 1140;
UPDATE mob_db SET kName = "Marina" WHERE ID = 1141;
UPDATE mob_db SET kName = "Sphère Marine" WHERE ID = 1142;
UPDATE mob_db SET kName = "Marionnette" WHERE ID = 1143;
UPDATE mob_db SET kName = "Marse" WHERE ID = 1144;
UPDATE mob_db SET kName = "Martin" WHERE ID = 1145;
UPDATE mob_db SET kName = "Matyr" WHERE ID = 1146;
UPDATE mob_db SET kName = "Maya" WHERE ID = 1147;
UPDATE mob_db SET kName = "Méduse" WHERE ID = 1148;
UPDATE mob_db SET kName = "Minorous" WHERE ID = 1149;
UPDATE mob_db SET kName = "Fleur de Lune" WHERE ID = 1150;
UPDATE mob_db SET kName = "Brume" WHERE ID = 1151;
UPDATE mob_db SET kName = "Squelette d'Orc" WHERE ID = 1152;
UPDATE mob_db SET kName = "Zombie d'Orc" WHERE ID = 1153;
UPDATE mob_db SET kName = "Pasana" WHERE ID = 1154;
UPDATE mob_db SET kName = "Petite" WHERE ID = 1155;
UPDATE mob_db SET kName = "Petite" WHERE ID = 1156;
UPDATE mob_db SET kName = "Pharaon" WHERE ID = 1157;
UPDATE mob_db SET kName = "Phen" WHERE ID = 1158;
UPDATE mob_db SET kName = "Phreeoni" WHERE ID = 1159;
UPDATE mob_db SET kName = "Pierre" WHERE ID = 1160;
UPDATE mob_db SET kName = "Plancton" WHERE ID = 1161;
UPDATE mob_db SET kName = "Rafflesia" WHERE ID = 1162;
UPDATE mob_db SET kName = "Raydric" WHERE ID = 1163;
UPDATE mob_db SET kName = "Requiem" WHERE ID = 1164;
UPDATE mob_db SET kName = "Sableux" WHERE ID = 1165;
UPDATE mob_db SET kName = "Sauvage" WHERE ID = 1166;
UPDATE mob_db SET kName = "Sauvageon" WHERE ID = 1167;
UPDATE mob_db SET kName = "Ouvrier Squelette" WHERE ID = 1169;
UPDATE mob_db SET kName = "Sohee" WHERE ID = 1170;
UPDATE mob_db SET kName = "Tacheté" WHERE ID = 1174;
UPDATE mob_db SET kName = "Tarou" WHERE ID = 1175;
UPDATE mob_db SET kName = "Vitata" WHERE ID = 1176;
UPDATE mob_db SET kName = "Zénorc" WHERE ID = 1177;
UPDATE mob_db SET kName = "Zérom" WHERE ID = 1178;
UPDATE mob_db SET kName = "Murmure" WHERE ID = 1179;
UPDATE mob_db SET kName = "Neuf Queues" WHERE ID = 1180;
UPDATE mob_db SET kName = "Champignon des Voleurs" WHERE ID = 1182;
UPDATE mob_db SET kName = "Chonchon" WHERE ID = 1183;
UPDATE mob_db SET kName = "Fabre" WHERE ID = 1184;
UPDATE mob_db SET kName = "Murmure" WHERE ID = 1185;
UPDATE mob_db SET kName = "Grand Murmure" WHERE ID = 1186;
UPDATE mob_db SET kName = "Switch" WHERE ID = 1187;
UPDATE mob_db SET kName = "Bongun" WHERE ID = 1188;
UPDATE mob_db SET kName = "Orc Archer" WHERE ID = 1189;
UPDATE mob_db SET kName = "Seigneur des Orcs" WHERE ID = 1190;
UPDATE mob_db SET kName = "Mimic" WHERE ID = 1191;
UPDATE mob_db SET kName = "Spectre" WHERE ID = 1192;
UPDATE mob_db SET kName = "Toquant" WHERE ID = 1193;
UPDATE mob_db SET kName = "Arclouse" WHERE ID = 1194;
UPDATE mob_db SET kName = "Verbousard" WHERE ID = 1195;
UPDATE mob_db SET kName = "Squelette Prisonnier" WHERE ID = 1196;
UPDATE mob_db SET kName = "Prisonnier Zombie" WHERE ID = 1197;
UPDATE mob_db SET kName = "Cultiste" WHERE ID = 1198;
UPDATE mob_db SET kName = "Punk" WHERE ID = 1199;
UPDATE mob_db SET kName = "Zherlthsh" WHERE ID = 1200;
UPDATE mob_db SET kName = "Rybio" WHERE ID = 1201;
UPDATE mob_db SET kName = "Phendark" WHERE ID = 1202;
UPDATE mob_db SET kName = "Mysteltainn" WHERE ID = 1203;
UPDATE mob_db SET kName = "Tirfing" WHERE ID = 1204;
UPDATE mob_db SET kName = "Exécuteur" WHERE ID = 1205;
UPDATE mob_db SET kName = "Anolien" WHERE ID = 1206;
UPDATE mob_db SET kName = "Bouserot" WHERE ID = 1207;
UPDATE mob_db SET kName = "Rôdeur" WHERE ID = 1208;
UPDATE mob_db SET kName = "Crampe" WHERE ID = 1209;
UPDATE mob_db SET kName = "Chamarré" WHERE ID = 1211;
UPDATE mob_db SET kName = "Poings de Fer" WHERE ID = 1212;
UPDATE mob_db SET kName = "Grand Orc" WHERE ID = 1213;
UPDATE mob_db SET kName = "Choco" WHERE ID = 1214;
UPDATE mob_db SET kName = "Pied-de-Ver" WHERE ID = 1215;
UPDATE mob_db SET kName = "Pénomena" WHERE ID = 1216;
UPDATE mob_db SET kName = "Chevalier des Abysses" WHERE ID = 1219;
UPDATE mob_db SET kName = "Loup du Désert" WHERE ID = 1220;
UPDATE mob_db SET kName = "Sauvage" WHERE ID = 1221;
UPDATE mob_db SET kName = "Grand Orc" WHERE ID = 1222;
UPDATE mob_db SET kName = "Spore Empoisonnée" WHERE ID = 1224;
UPDATE mob_db SET kName = "Choco" WHERE ID = 1225;
UPDATE mob_db SET kName = "Kobold" WHERE ID = 1226;
UPDATE mob_db SET kName = "Gobelin" WHERE ID = 1227;
UPDATE mob_db SET kName = "Phen" WHERE ID = 1228;
UPDATE mob_db SET kName = "Fabre" WHERE ID = 1229;
UPDATE mob_db SET kName = "Chrysalide" WHERE ID = 1230;
UPDATE mob_db SET kName = "Crémeux" WHERE ID = 1231;
UPDATE mob_db SET kName = "Oeuf de Péco Péco" WHERE ID = 1232;
UPDATE mob_db SET kName = "Péco Péco" WHERE ID = 1233;
UPDATE mob_db SET kName = "Yoyo" WHERE ID = 1234;
UPDATE mob_db SET kName = "Orc Toxicomane" WHERE ID = 1235;
UPDATE mob_db SET kName = "Oeuf de Fourmi" WHERE ID = 1236;
UPDATE mob_db SET kName = "André" WHERE ID = 1237;
UPDATE mob_db SET kName = "Pierre" WHERE ID = 1238;
UPDATE mob_db SET kName = "Deniro" WHERE ID = 1239;
UPDATE mob_db SET kName = "Picky" WHERE ID = 1240;
UPDATE mob_db SET kName = "Picky" WHERE ID = 1241;
UPDATE mob_db SET kName = "Marin" WHERE ID = 1242;
UPDATE mob_db SET kName = "Sasquatch" WHERE ID = 1243;
UPDATE mob_db SET kName = "Jack de Noël" WHERE ID = 1244;
UPDATE mob_db SET kName = "Gobelin de Noël" WHERE ID = 1245;
UPDATE mob_db SET kName = "Cookie de Noël" WHERE ID = 1246;
UPDATE mob_db SET kName = "Antonio" WHERE ID = 1247;
UPDATE mob_db SET kName = "Petit Soldat" WHERE ID = 1248;
UPDATE mob_db SET kName = "Cadeau Surprise" WHERE ID = 1249;
UPDATE mob_db SET kName = "Chépette" WHERE ID = 1250;
UPDATE mob_db SET kName = "Chevalier de Glace" WHERE ID = 1251;
UPDATE mob_db SET kName = "Garm" WHERE ID = 1252;
UPDATE mob_db SET kName = "Gargouille" WHERE ID = 1253;
UPDATE mob_db SET kName = "Loquerot" WHERE ID = 1254;
UPDATE mob_db SET kName = "Néréïde" WHERE ID = 1255;
UPDATE mob_db SET kName = "Peste" WHERE ID = 1256;
UPDATE mob_db SET kName = "Injustice" WHERE ID = 1257;
UPDATE mob_db SET kName = "Archer Gobelin" WHERE ID = 1258;
UPDATE mob_db SET kName = "Griffon" WHERE ID = 1259;
UPDATE mob_db SET kName = "Sombre Reflet" WHERE ID = 1260;
UPDATE mob_db SET kName = "Bruterose" WHERE ID = 1261;
UPDATE mob_db SET kName = "Dragonoïde Mutant" WHERE ID = 1262;
UPDATE mob_db SET kName = "Esprit Venteux" WHERE ID = 1263;
UPDATE mob_db SET kName = "Poissonard" WHERE ID = 1264;
UPDATE mob_db SET kName = "Cookie" WHERE ID = 1265;
UPDATE mob_db SET kName = "Aster" WHERE ID = 1266;
UPDATE mob_db SET kName = "Carat" WHERE ID = 1267;
UPDATE mob_db SET kName = "Chevalier Sanguinaire" WHERE ID = 1268;
UPDATE mob_db SET kName = "Pendulard" WHERE ID = 1269;
UPDATE mob_db SET kName = "Gardien de l'Horloge" WHERE ID = 1270;
UPDATE mob_db SET kName = "Alligator" WHERE ID = 1271;
UPDATE mob_db SET kName = "Seigneur des Ténèbres" WHERE ID = 1272;
UPDATE mob_db SET kName = "Orc Femelle" WHERE ID = 1273;
UPDATE mob_db SET kName = "Mégalite" WHERE ID = 1274;
UPDATE mob_db SET kName = "Alice" WHERE ID = 1275;
UPDATE mob_db SET kName = "Archer Raydric" WHERE ID = 1276;
UPDATE mob_db SET kName = "Général Sérénissime" WHERE ID = 1277;
UPDATE mob_db SET kName = "Stalagol" WHERE ID = 1278;
UPDATE mob_db SET kName = "Tri Joint" WHERE ID = 1279;
UPDATE mob_db SET kName = "Héli-Gobelin" WHERE ID = 1280;
UPDATE mob_db SET kName = "Sagever" WHERE ID = 1281;
UPDATE mob_db SET kName = "Kobold Archer" WHERE ID = 1282;
UPDATE mob_db SET kName = "Chimère" WHERE ID = 1283;
UPDATE mob_db SET kName = "Guardien Archer" WHERE ID = 1285;
UPDATE mob_db SET kName = "Guardien Chevalier" WHERE ID = 1286;
UPDATE mob_db SET kName = "Guardien Soldat" WHERE ID = 1287;
UPDATE mob_db SET kName = "Emperium" WHERE ID = 1288;
UPDATE mob_db SET kName = "Maya Violette" WHERE ID = 1289;
UPDATE mob_db SET kName = "Squelette Général" WHERE ID = 1290;
UPDATE mob_db SET kName = "Spectre de Mort" WHERE ID = 1291;
UPDATE mob_db SET kName = "Mini-Démon" WHERE ID = 1292;
UPDATE mob_db SET kName = "Sombre Crémeux" WHERE ID = 1293;
UPDATE mob_db SET kName = "Mante Tueuse" WHERE ID = 1294;
UPDATE mob_db SET kName = "Chouette Effraie" WHERE ID = 1295;
UPDATE mob_db SET kName = "Chef Kobold" WHERE ID = 1296;
UPDATE mob_db SET kName = "Ancienne Momie" WHERE ID = 1297;
UPDATE mob_db SET kName = "Maître Zombie" WHERE ID = 1298;
UPDATE mob_db SET kName = "Chef Gobelin" WHERE ID = 1299;
UPDATE mob_db SET kName = "Chenille" WHERE ID = 1300;
UPDATE mob_db SET kName = "Am Mut" WHERE ID = 1301;
UPDATE mob_db SET kName = "Illusion des Ténèbres" WHERE ID = 1302;
UPDATE mob_db SET kName = "Frelon Géant" WHERE ID = 1303;
UPDATE mob_db SET kName = "Araignée Géante" WHERE ID = 1304;
UPDATE mob_db SET kName = "Ver Ancien" WHERE ID = 1305;
UPDATE mob_db SET kName = "Leib Olmai" WHERE ID = 1306;
UPDATE mob_db SET kName = "Chat aux Neuf Queues" WHERE ID = 1307;
UPDATE mob_db SET kName = "Panzer Gobelin" WHERE ID = 1308;
UPDATE mob_db SET kName = "Gajomart" WHERE ID = 1309;
UPDATE mob_db SET kName = "Majoruros" WHERE ID = 1310;
UPDATE mob_db SET kName = "Gullinbursti" WHERE ID = 1311;
UPDATE mob_db SET kName = "Général Tortue" WHERE ID = 1312;
UPDATE mob_db SET kName = "Mobster" WHERE ID = 1313;
UPDATE mob_db SET kName = "Permeter" WHERE ID = 1314;
UPDATE mob_db SET kName = "Assaillant" WHERE ID = 1315;
UPDATE mob_db SET kName = "Solidard" WHERE ID = 1316;
UPDATE mob_db SET kName = "Phoque" WHERE ID = 1317;
UPDATE mob_db SET kName = "Brûleur" WHERE ID = 1318;
UPDATE mob_db SET kName = "Cœur-de-Glace" WHERE ID = 1319;
UPDATE mob_db SET kName = "Grand-Duc" WHERE ID = 1320;
UPDATE mob_db SET kName = "Queue-de-Dragon" WHERE ID = 1321;
UPDATE mob_db SET kName = "Lapin Bondissant" WHERE ID = 1322;
UPDATE mob_db SET kName = "Loutre de Mer" WHERE ID = 1323;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1324;
UPDATE mob_db SET kName = "Coffre Chest" WHERE ID = 1325;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1326;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1327;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1328;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1329;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1330;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1331;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1332;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1333;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1334;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1335;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1336;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1337;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1338;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1339;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1340;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1341;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1342;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1343;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1344;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1345;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1346;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1347;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1348;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1349;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1350;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1351;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1352;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1353;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1354;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1355;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1356;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1357;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1358;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1359;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1360;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1361;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1362;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1363;
UPDATE mob_db SET kName = "Assaillant" WHERE ID = 1364;
UPDATE mob_db SET kName = "Apocalypse" WHERE ID = 1365;
UPDATE mob_db SET kName = "Golem de Lave" WHERE ID = 1366;
UPDATE mob_db SET kName = "Flambeur" WHERE ID = 1367;
UPDATE mob_db SET kName = "Géographe" WHERE ID = 1368;
UPDATE mob_db SET kName = "Grand Péco" WHERE ID = 1369;
UPDATE mob_db SET kName = "Succube" WHERE ID = 1370;
UPDATE mob_db SET kName = "Ange Impie" WHERE ID = 1371;
UPDATE mob_db SET kName = "Bouc" WHERE ID = 1372;
UPDATE mob_db SET kName = "Seigneur de la Mort" WHERE ID = 1373;
UPDATE mob_db SET kName = "Incube" WHERE ID = 1374;
UPDATE mob_db SET kName = "Le Papelard" WHERE ID = 1375;
UPDATE mob_db SET kName = "Harpie" WHERE ID = 1376;
UPDATE mob_db SET kName = "L'Ancien" WHERE ID = 1377;
UPDATE mob_db SET kName = "Démon Pungus" WHERE ID = 1378;
UPDATE mob_db SET kName = "Cauchemar Terrifiant" WHERE ID = 1379;
UPDATE mob_db SET kName = "Foreur" WHERE ID = 1380;
UPDATE mob_db SET kName = "Grizzly" WHERE ID = 1381;
UPDATE mob_db SET kName = "Diabolique" WHERE ID = 1382;
UPDATE mob_db SET kName = "Explosion" WHERE ID = 1383;
UPDATE mob_db SET kName = "Deleter" WHERE ID = 1384;
UPDATE mob_db SET kName = "Deleter" WHERE ID = 1385;
UPDATE mob_db SET kName = "Dormeur" WHERE ID = 1386;
UPDATE mob_db SET kName = "Harponneur" WHERE ID = 1387;
UPDATE mob_db SET kName = "Archangéling" WHERE ID = 1388;
UPDATE mob_db SET kName = "Dracula" WHERE ID = 1389;
UPDATE mob_db SET kName = "Violie" WHERE ID = 1390;
UPDATE mob_db SET kName = "Galapago" WHERE ID = 1391;
UPDATE mob_db SET kName = "Rotar Zairo" WHERE ID = 1392;
UPDATE mob_db SET kName = "Momie" WHERE ID = 1393;
UPDATE mob_db SET kName = "Zombie" WHERE ID = 1394;
UPDATE mob_db SET kName = "Cristal de Vent" WHERE ID = 1395;
UPDATE mob_db SET kName = "Cristal de Terre" WHERE ID = 1396;
UPDATE mob_db SET kName = "Cristal de Feu" WHERE ID = 1397;
UPDATE mob_db SET kName = "Cristal d'Eau" WHERE ID = 1398;
UPDATE mob_db SET kName = "Baphomet" WHERE ID = 1399;
UPDATE mob_db SET kName = "Karakasa" WHERE ID = 1400;
UPDATE mob_db SET kName = "Shinobi" WHERE ID = 1401;
UPDATE mob_db SET kName = "Crapaud Venimeux" WHERE ID = 1402;
UPDATE mob_db SET kName = "Ancien Arquebusier" WHERE ID = 1403;
UPDATE mob_db SET kName = "Miyabi Ningyo" WHERE ID = 1404;
UPDATE mob_db SET kName = "Tengu" WHERE ID = 1405;
UPDATE mob_db SET kName = "Kapha" WHERE ID = 1406;
UPDATE mob_db SET kName = "Papillon Sanguinaire" WHERE ID = 1408;
UPDATE mob_db SET kName = "Rice Cake Boy" WHERE ID = 1409;
UPDATE mob_db SET kName = "Pêcher Vivant" WHERE ID = 1410;
UPDATE mob_db SET kName = "Ermite Céleste" WHERE ID = 1412;
UPDATE mob_db SET kName = "Ginseng Sauvage" WHERE ID = 1413;
UPDATE mob_db SET kName = "Jeune Léopard" WHERE ID = 1415;
UPDATE mob_db SET kName = "Nymphe Maléfique" WHERE ID = 1416;
UPDATE mob_db SET kName = "Nounours" WHERE ID = 1417;
UPDATE mob_db SET kName = "Seigneur des Serpents" WHERE ID = 1418;
UPDATE mob_db SET kName = "Familier" WHERE ID = 1419;
UPDATE mob_db SET kName = "Squelette Archer" WHERE ID = 1420;
UPDATE mob_db SET kName = "Isis" WHERE ID = 1421;
UPDATE mob_db SET kName = "Mouche Guerrière" WHERE ID = 1422;
UPDATE mob_db SET kName = "Goule" WHERE ID = 1423;
UPDATE mob_db SET kName = "Vipère" WHERE ID = 1424;
UPDATE mob_db SET kName = "Obeaune" WHERE ID = 1425;
UPDATE mob_db SET kName = "Marc" WHERE ID = 1426;
UPDATE mob_db SET kName = "Cauchemar" WHERE ID = 1427;
UPDATE mob_db SET kName = "Spore Empoisonnée" WHERE ID = 1428;
UPDATE mob_db SET kName = "Argiope" WHERE ID = 1429;
UPDATE mob_db SET kName = "Argos" WHERE ID = 1430;
UPDATE mob_db SET kName = "Baphomet Jr." WHERE ID = 1431;
UPDATE mob_db SET kName = "Loup du Désert" WHERE ID = 1432;
UPDATE mob_db SET kName = "Deviruchi" WHERE ID = 1433;
UPDATE mob_db SET kName = "Drainlier" WHERE ID = 1434;
UPDATE mob_db SET kName = "Druide Maléfique" WHERE ID = 1435;
UPDATE mob_db SET kName = "Jack" WHERE ID = 1436;
UPDATE mob_db SET kName = "Joker" WHERE ID = 1437;
UPDATE mob_db SET kName = "Khalitzburg" WHERE ID = 1438;
UPDATE mob_db SET kName = "Grand Orc" WHERE ID = 1439;
UPDATE mob_db SET kName = "Pied-de-Ver" WHERE ID = 1440;
UPDATE mob_db SET kName = "Pénomena" WHERE ID = 1441;
UPDATE mob_db SET kName = "Sasquatch" WHERE ID = 1442;
UPDATE mob_db SET kName = "Petit Soldat" WHERE ID = 1443;
UPDATE mob_db SET kName = "Chépette" WHERE ID = 1444;
UPDATE mob_db SET kName = "Loquerot" WHERE ID = 1445;
UPDATE mob_db SET kName = "Injustice" WHERE ID = 1446;
UPDATE mob_db SET kName = "Griffon" WHERE ID = 1447;
UPDATE mob_db SET kName = "Sombre Reflet" WHERE ID = 1448;
UPDATE mob_db SET kName = "Dragonoïde Mutant" WHERE ID = 1449;
UPDATE mob_db SET kName = "Esprit Ventuex" WHERE ID = 1450;
UPDATE mob_db SET kName = "Poissonard" WHERE ID = 1451;
UPDATE mob_db SET kName = "Orc Femelle" WHERE ID = 1452;
UPDATE mob_db SET kName = "Archer Raydric" WHERE ID = 1453;
UPDATE mob_db SET kName = "Tri Joint" WHERE ID = 1454;
UPDATE mob_db SET kName = "Kobold Archer" WHERE ID = 1455;
UPDATE mob_db SET kName = "Chimère" WHERE ID = 1456;
UPDATE mob_db SET kName = "Mante" WHERE ID = 1457;
UPDATE mob_db SET kName = "Marduk" WHERE ID = 1458;
UPDATE mob_db SET kName = "Marionnette" WHERE ID = 1459;
UPDATE mob_db SET kName = "Matyr" WHERE ID = 1460;
UPDATE mob_db SET kName = "Minorous" WHERE ID = 1461;
UPDATE mob_db SET kName = "Squelette d'Orc" WHERE ID = 1462;
UPDATE mob_db SET kName = "Zombie d'Orc" WHERE ID = 1463;
UPDATE mob_db SET kName = "Pasana" WHERE ID = 1464;
UPDATE mob_db SET kName = "Petite" WHERE ID = 1465;
UPDATE mob_db SET kName = "Petite" WHERE ID = 1466;
UPDATE mob_db SET kName = "Raydric" WHERE ID = 1467;
UPDATE mob_db SET kName = "Requim" WHERE ID = 1468;
UPDATE mob_db SET kName = "Ouvrier Squelette" WHERE ID = 1469;
UPDATE mob_db SET kName = "Zérom" WHERE ID = 1470;
UPDATE mob_db SET kName = "Neuf Queues" WHERE ID = 1471;
UPDATE mob_db SET kName = "Bongun" WHERE ID = 1472;
UPDATE mob_db SET kName = "Orc Archer" WHERE ID = 1473;
UPDATE mob_db SET kName = "Mimic" WHERE ID = 1474;
UPDATE mob_db SET kName = "Spectre" WHERE ID = 1475;
UPDATE mob_db SET kName = "Toquant" WHERE ID = 1476;
UPDATE mob_db SET kName = "Arclouse" WHERE ID = 1477;
UPDATE mob_db SET kName = "Verbousard" WHERE ID = 1478;
UPDATE mob_db SET kName = "Squelette Prisonnier" WHERE ID = 1479;
UPDATE mob_db SET kName = "Prisonnier Zombie" WHERE ID = 1480;
UPDATE mob_db SET kName = "Punk" WHERE ID = 1481;
UPDATE mob_db SET kName = "Zherlthsh" WHERE ID = 1482;
UPDATE mob_db SET kName = "Rybio" WHERE ID = 1483;
UPDATE mob_db SET kName = "Phendark" WHERE ID = 1484;
UPDATE mob_db SET kName = "Mysteltainn" WHERE ID = 1485;
UPDATE mob_db SET kName = "Tirfing" WHERE ID = 1486;
UPDATE mob_db SET kName = "Exécuteur" WHERE ID = 1487;
UPDATE mob_db SET kName = "Anolien" WHERE ID = 1488;
UPDATE mob_db SET kName = "Bouserot" WHERE ID = 1489;
UPDATE mob_db SET kName = "Rôdeur" WHERE ID = 1490;
UPDATE mob_db SET kName = "Dokebi" WHERE ID = 1491;
UPDATE mob_db SET kName = "Samurai Réincarné" WHERE ID = 1492;
UPDATE mob_db SET kName = "Dryade" WHERE ID = 1493;
UPDATE mob_db SET kName = "Roi des Cafards" WHERE ID = 1494;
UPDATE mob_db SET kName = "Frapardeur" WHERE ID = 1495;
UPDATE mob_db SET kName = "Golem de Bois" WHERE ID = 1497;
UPDATE mob_db SET kName = "Tirailleur Boisard" WHERE ID = 1498;
UPDATE mob_db SET kName = "Combattant Boisard" WHERE ID = 1499;
UPDATE mob_db SET kName = "Parasite" WHERE ID = 1500;
UPDATE mob_db SET kName = "Pori Pori" WHERE ID = 1502;
UPDATE mob_db SET kName = "Gibbet" WHERE ID = 1503;
UPDATE mob_db SET kName = "Dullahan" WHERE ID = 1504;
UPDATE mob_db SET kName = "Loli Ruri" WHERE ID = 1505;
UPDATE mob_db SET kName = "Camouflard" WHERE ID = 1506;
UPDATE mob_db SET kName = "Meurtrier Sanguinaire" WHERE ID = 1507;
UPDATE mob_db SET kName = "Quve" WHERE ID = 1508;
UPDATE mob_db SET kName = "Lude" WHERE ID = 1509;
UPDATE mob_db SET kName = "Hylozoïste" WHERE ID = 1510;
UPDATE mob_db SET kName = "Amon Ra" WHERE ID = 1511;
UPDATE mob_db SET kName = "Hyegun" WHERE ID = 1512;
UPDATE mob_db SET kName = "Mao Guai" WHERE ID = 1513;
UPDATE mob_db SET kName = "Dragon Danseur" WHERE ID = 1514;
UPDATE mob_db SET kName = "Jeune Garm" WHERE ID = 1515;
UPDATE mob_db SET kName = "Mi Gao" WHERE ID = 1516;
UPDATE mob_db SET kName = "Li Me Mang Ryang" WHERE ID = 1517;
UPDATE mob_db SET kName = "Bacsojin" WHERE ID = 1518;
UPDATE mob_db SET kName = "Chung Li" WHERE ID = 1519;
UPDATE mob_db SET kName = "Riz Vapeur" WHERE ID = 1520;
UPDATE mob_db SET kName = "Alice" WHERE ID = 1521;
UPDATE mob_db SET kName = "Ancienne Momie" WHERE ID = 1522;
UPDATE mob_db SET kName = "Ancien Arquebusier" WHERE ID = 1523;
UPDATE mob_db SET kName = "Jeune Léopard" WHERE ID = 1524;
UPDATE mob_db SET kName = "Bathory" WHERE ID = 1525;
UPDATE mob_db SET kName = "Papillon Sanguinaire" WHERE ID = 1526;
UPDATE mob_db SET kName = "Gardien de l'Horloge" WHERE ID = 1527;
UPDATE mob_db SET kName = "Pendulard" WHERE ID = 1528;
UPDATE mob_db SET kName = "Seigneur des Serpents" WHERE ID = 1529;
UPDATE mob_db SET kName = "Dracula" WHERE ID = 1530;
UPDATE mob_db SET kName = "Ermite Céleste" WHERE ID = 1531;
UPDATE mob_db SET kName = "Explosion" WHERE ID = 1532;
UPDATE mob_db SET kName = "Phoque" WHERE ID = 1533;
UPDATE mob_db SET kName = "Gobelin" WHERE ID = 1534;
UPDATE mob_db SET kName = "Gobelin" WHERE ID = 1535;
UPDATE mob_db SET kName = "Gobelin" WHERE ID = 1536;
UPDATE mob_db SET kName = "Gobelin" WHERE ID = 1537;
UPDATE mob_db SET kName = "Gobelin" WHERE ID = 1538;
UPDATE mob_db SET kName = "Chef Gobelin" WHERE ID = 1539;
UPDATE mob_db SET kName = "Golem" WHERE ID = 1540;
UPDATE mob_db SET kName = "Général Sérénissime" WHERE ID = 1541;
UPDATE mob_db SET kName = "Samouraï Réincarné" WHERE ID = 1542;
UPDATE mob_db SET kName = "Kapha" WHERE ID = 1543;
UPDATE mob_db SET kName = "Karakasa" WHERE ID = 1544;
UPDATE mob_db SET kName = "Kobold" WHERE ID = 1545;
UPDATE mob_db SET kName = "Kobold" WHERE ID = 1546;
UPDATE mob_db SET kName = "Kobold" WHERE ID = 1547;
UPDATE mob_db SET kName = "Chef Kobold" WHERE ID = 1548;
UPDATE mob_db SET kName = "Golem de Lave" WHERE ID = 1549;
UPDATE mob_db SET kName = "Pêcher Vivant" WHERE ID = 1550;
UPDATE mob_db SET kName = "Marse" WHERE ID = 1551;
UPDATE mob_db SET kName = "Miyabi Ningyo" WHERE ID = 1552;
UPDATE mob_db SET kName = "Brume" WHERE ID = 1553;
UPDATE mob_db SET kName = "Cauchemar Terrifiant" WHERE ID = 1554;
UPDATE mob_db SET kName = "Parasite" WHERE ID = 1555;
UPDATE mob_db SET kName = "Crapaud Venimeux" WHERE ID = 1556;
UPDATE mob_db SET kName = "Rotar Zairo" WHERE ID = 1557;
UPDATE mob_db SET kName = "Sableux" WHERE ID = 1558;
UPDATE mob_db SET kName = "Scorpion" WHERE ID = 1559;
UPDATE mob_db SET kName = "Shinobi" WHERE ID = 1560;
UPDATE mob_db SET kName = "Smokie" WHERE ID = 1561;
UPDATE mob_db SET kName = "Squelette Soldat" WHERE ID = 1562;
UPDATE mob_db SET kName = "Tengu" WHERE ID = 1563;
UPDATE mob_db SET kName = "Nymphe Maléfique" WHERE ID = 1564;
UPDATE mob_db SET kName = "Ginseng Sauvage" WHERE ID = 1565;
UPDATE mob_db SET kName = "Spectre de Mort" WHERE ID = 1566;
UPDATE mob_db SET kName = "Ver Ancien" WHERE ID = 1567;
UPDATE mob_db SET kName = "Angéling" WHERE ID = 1568;
UPDATE mob_db SET kName = "Chevalier Sanguinaire" WHERE ID = 1569;
UPDATE mob_db SET kName = "Crampe" WHERE ID = 1570;
UPDATE mob_db SET kName = "Déviace" WHERE ID = 1571;
UPDATE mob_db SET kName = "Drops" WHERE ID = 1572;
UPDATE mob_db SET kName = "L'Ancien" WHERE ID = 1573;
UPDATE mob_db SET kName = "Saule Ancien" WHERE ID = 1574;
UPDATE mob_db SET kName = "Flora" WHERE ID = 1575;
UPDATE mob_db SET kName = "Ghostring" WHERE ID = 1576;
UPDATE mob_db SET kName = "Archer Gobelin" WHERE ID = 1577;
UPDATE mob_db SET kName = "Horong" WHERE ID = 1578;
UPDATE mob_db SET kName = "Hydre" WHERE ID = 1579;
UPDATE mob_db SET kName = "Incube" WHERE ID = 1580;
UPDATE mob_db SET kName = "Vocal" WHERE ID = 1581;
UPDATE mob_db SET kName = "Déviling" WHERE ID = 1582;
UPDATE mob_db SET kName = "Tao Gunka" WHERE ID = 1583;
UPDATE mob_db SET kName = "Tamruan" WHERE ID = 1584;
UPDATE mob_db SET kName = "Singe Singeur" WHERE ID = 1585;
UPDATE mob_db SET kName = "Chat Sylvestre" WHERE ID = 1586;
UPDATE mob_db SET kName = "Kraben" WHERE ID = 1587;
UPDATE mob_db SET kName = "Orc de Noël" WHERE ID = 1588;
UPDATE mob_db SET kName = "Mandragore" WHERE ID = 1589;
UPDATE mob_db SET kName = "Géographe" WHERE ID = 1590;
UPDATE mob_db SET kName = "Lunatique" WHERE ID = 1591;
UPDATE mob_db SET kName = "Gangster" WHERE ID = 1592;
UPDATE mob_db SET kName = "Ancienne Momie" WHERE ID = 1593;
UPDATE mob_db SET kName = "Cœur-de-Glace" WHERE ID = 1594;
UPDATE mob_db SET kName = "Marin" WHERE ID = 1595;
UPDATE mob_db SET kName = "Tamruan" WHERE ID = 1596;
UPDATE mob_db SET kName = "Gargouille" WHERE ID = 1597;
UPDATE mob_db SET kName = "Flambeur" WHERE ID = 1598;
UPDATE mob_db SET kName = "Grand Murmure" WHERE ID = 1599;
UPDATE mob_db SET kName = "Brûleur" WHERE ID = 1600;
UPDATE mob_db SET kName = "Permeter" WHERE ID = 1601;
UPDATE mob_db SET kName = "Solidard" WHERE ID = 1602;
UPDATE mob_db SET kName = "Yéti" WHERE ID = 1603;
UPDATE mob_db SET kName = "Frelon Géant" WHERE ID = 1604;
UPDATE mob_db SET kName = "Illusion des Ténèbres" WHERE ID = 1605;
UPDATE mob_db SET kName = "Jeune Garm" WHERE ID = 1606;
UPDATE mob_db SET kName = "Gobelin de Noël" WHERE ID = 1607;
UPDATE mob_db SET kName = "Grand Chapardeur" WHERE ID = 1608;
UPDATE mob_db SET kName = "Dragon Danseur" WHERE ID = 1609;
UPDATE mob_db SET kName = "Munak" WHERE ID = 1610;
UPDATE mob_db SET kName = "Bongun" WHERE ID = 1611;
UPDATE mob_db SET kName = "Hyegun" WHERE ID = 1612;
UPDATE mob_db SET kName = "Métaling" WHERE ID = 1613;
UPDATE mob_db SET kName = "Minéral" WHERE ID = 1614;
UPDATE mob_db SET kName = "Obsidien" WHERE ID = 1615;
UPDATE mob_db SET kName = "Mineur" WHERE ID = 1616;
UPDATE mob_db SET kName = "Vieux Fourneau" WHERE ID = 1617;
UPDATE mob_db SET kName = "Ungoliant" WHERE ID = 1618;
UPDATE mob_db SET kName = "Porcellio" WHERE ID = 1619;
UPDATE mob_db SET kName = "Nocif" WHERE ID = 1620;
UPDATE mob_db SET kName = "Venimeux" WHERE ID = 1621;
UPDATE mob_db SET kName = "Ours en Peluche" WHERE ID = 1622;
UPDATE mob_db SET kName = "RSX 0806" WHERE ID = 1623;
UPDATE mob_db SET kName = "Vieux Fourneau" WHERE ID = 1624;
UPDATE mob_db SET kName = "Porcellio" WHERE ID = 1625;
UPDATE mob_db SET kName = "Revenant d'Hellion" WHERE ID = 1626;
UPDATE mob_db SET kName = "Anophélès" WHERE ID = 1627;
UPDATE mob_db SET kName = "Taupe" WHERE ID = 1628;
UPDATE mob_db SET kName = "Vent des Collines" WHERE ID = 1629;
UPDATE mob_db SET kName = "Bacsojin" WHERE ID = 1630;
UPDATE mob_db SET kName = "Chung Li" WHERE ID = 1631;
UPDATE mob_db SET kName = "Gremlin" WHERE ID = 1632;
UPDATE mob_db SET kName = "Scruteur" WHERE ID = 1633;
UPDATE mob_db SET kName = "Seyren Windsor" WHERE ID = 1634;
UPDATE mob_db SET kName = "Eremes Guile" WHERE ID = 1635;
UPDATE mob_db SET kName = "Howard Alt-Eisen" WHERE ID = 1636;
UPDATE mob_db SET kName = "Margaretha Sorin" WHERE ID = 1637;
UPDATE mob_db SET kName = "Cecil Damon" WHERE ID = 1638;
UPDATE mob_db SET kName = "Kathryne Keyron" WHERE ID = 1639;
UPDATE mob_db SET kName = "Chevalier Seyren" WHERE ID = 1640;
UPDATE mob_db SET kName = "Assassin Cross Eremes" WHERE ID = 1641;
UPDATE mob_db SET kName = "Maître Forgeron Howard" WHERE ID = 1642;
UPDATE mob_db SET kName = "Prêtresse Margaretha" WHERE ID = 1643;
UPDATE mob_db SET kName = "Tireur d'Elite Cecil" WHERE ID = 1644;
UPDATE mob_db SET kName = "Sorcière Kathryne" WHERE ID = 1645;
UPDATE mob_db SET kName = "Chevalier Seyren" WHERE ID = 1646;
UPDATE mob_db SET kName = "Assassin Cross Eremes" WHERE ID = 1647;
UPDATE mob_db SET kName = "Maître Forgeron Howard" WHERE ID = 1648;
UPDATE mob_db SET kName = "Prêtresse Margaretha" WHERE ID = 1649;
UPDATE mob_db SET kName = "Tireur d'Élite Cecil" WHERE ID = 1650;
UPDATE mob_db SET kName = "Sorcière Kathryne" WHERE ID = 1651;
UPDATE mob_db SET kName = "Egnigem Cenia" WHERE ID = 1652;
UPDATE mob_db SET kName = "Whikebain" WHERE ID = 1653;
UPDATE mob_db SET kName = "Armaia" WHERE ID = 1654;
UPDATE mob_db SET kName = "Erend" WHERE ID = 1655;
UPDATE mob_db SET kName = "Kavac" WHERE ID = 1656;
UPDATE mob_db SET kName = "Laurell Weinder" WHERE ID = 1657;
UPDATE mob_db SET kName = "Egnigem Cenia" WHERE ID = 1658;
UPDATE mob_db SET kName = "Whikebain" WHERE ID = 1659;
UPDATE mob_db SET kName = "Armaia" WHERE ID = 1660;
UPDATE mob_db SET kName = "Erend" WHERE ID = 1661;
UPDATE mob_db SET kName = "Kavac" WHERE ID = 1662;
UPDATE mob_db SET kName = "Laurell Weinder" WHERE ID = 1663;
UPDATE mob_db SET kName = "Photo-Cannon" WHERE ID = 1664;
UPDATE mob_db SET kName = "Photo-Canon" WHERE ID = 1665;
UPDATE mob_db SET kName = "Photo-Canon" WHERE ID = 1666;
UPDATE mob_db SET kName = "Photo-Canon" WHERE ID = 1667;
UPDATE mob_db SET kName = "Archdam" WHERE ID = 1668;
UPDATE mob_db SET kName = "Dimik" WHERE ID = 1669;
UPDATE mob_db SET kName = "Dimik" WHERE ID = 1670;
UPDATE mob_db SET kName = "Dimik" WHERE ID = 1671;
UPDATE mob_db SET kName = "Dimik" WHERE ID = 1672;
UPDATE mob_db SET kName = "Dimik" WHERE ID = 1673;
UPDATE mob_db SET kName = "Monemus" WHERE ID = 1674;
UPDATE mob_db SET kName = "Venatu" WHERE ID = 1675;
UPDATE mob_db SET kName = "Venatu" WHERE ID = 1676;
UPDATE mob_db SET kName = "Venatu" WHERE ID = 1677;
UPDATE mob_db SET kName = "Venatu" WHERE ID = 1678;
UPDATE mob_db SET kName = "Venatu" WHERE ID = 1679;
UPDATE mob_db SET kName = "Vent des Collines" WHERE ID = 1680;
UPDATE mob_db SET kName = "Gemini-S58" WHERE ID = 1681;
UPDATE mob_db SET kName = "Éradicateur" WHERE ID = 1682;
UPDATE mob_db SET kName = "Photo-Canon" WHERE ID = 1683;
UPDATE mob_db SET kName = "Archdam" WHERE ID = 1684;
UPDATE mob_db SET kName = "Vesper" WHERE ID = 1685;
UPDATE mob_db SET kName = "Jeune Orc" WHERE ID = 1686;
UPDATE mob_db SET kName = "Gecko" WHERE ID = 1687;
UPDATE mob_db SET kName = "Dame Tanee" WHERE ID = 1688;
UPDATE mob_db SET kName = "Bacsojin" WHERE ID = 1689;
UPDATE mob_db SET kName = "Lapin Bondissant" WHERE ID = 1690;
UPDATE mob_db SET kName = "Kraben" WHERE ID = 1691;
UPDATE mob_db SET kName = "Souffle" WHERE ID = 1692;
UPDATE mob_db SET kName = "Plasma" WHERE ID = 1693;
UPDATE mob_db SET kName = "Plasma" WHERE ID = 1694;
UPDATE mob_db SET kName = "Plasma" WHERE ID = 1695;
UPDATE mob_db SET kName = "Plasma" WHERE ID = 1696;
UPDATE mob_db SET kName = "Plasma" WHERE ID = 1697;
UPDATE mob_db SET kName = "Litanie Funèbre" WHERE ID = 1698;
UPDATE mob_db SET kName = "Ancienne Mimic" WHERE ID = 1699;
UPDATE mob_db SET kName = "Observation" WHERE ID = 1700;
UPDATE mob_db SET kName = "Maîtresse du Foyer" WHERE ID = 1701;
UPDATE mob_db SET kName = "Baronne Rétribution" WHERE ID = 1702;
UPDATE mob_db SET kName = "Dame Récomfort" WHERE ID = 1703;
UPDATE mob_db SET kName = "Haine de Thanatos" WHERE ID = 1704;
UPDATE mob_db SET kName = "Désespoir de Thanatos" WHERE ID = 1705;
UPDATE mob_db SET kName = "Tristesse de Thanatos" WHERE ID = 1706;
UPDATE mob_db SET kName = "Agonie de Thanatos" WHERE ID = 1707;
UPDATE mob_db SET kName = "Thanatos" WHERE ID = 1708;
UPDATE mob_db SET kName = "Haine de Thanatos" WHERE ID = 1709;
UPDATE mob_db SET kName = "Désespoir de Thanatos" WHERE ID = 1710;
UPDATE mob_db SET kName = "Tristesse de Thanatos" WHERE ID = 1711;
UPDATE mob_db SET kName = "Agonie de Thanatos" WHERE ID = 1712;
UPDATE mob_db SET kName = "Acidus" WHERE ID = 1713;
UPDATE mob_db SET kName = "Férus" WHERE ID = 1714;
UPDATE mob_db SET kName = "Novus" WHERE ID = 1715;
UPDATE mob_db SET kName = "Acidus" WHERE ID = 1716;
UPDATE mob_db SET kName = "Férus" WHERE ID = 1717;
UPDATE mob_db SET kName = "Novus" WHERE ID = 1718;
UPDATE mob_db SET kName = "Détale" WHERE ID = 1719;
UPDATE mob_db SET kName = "Hydro" WHERE ID = 1720;
UPDATE mob_db SET kName = "Oeuf de Dragon" WHERE ID = 1721;
UPDATE mob_db SET kName = "Jack" WHERE ID = 1722;
UPDATE mob_db SET kName = "Cecil Damon" WHERE ID = 1723;
UPDATE mob_db SET kName = "Photo-Canon" WHERE ID = 1724;
UPDATE mob_db SET kName = "Poring" WHERE ID = 1725;
UPDATE mob_db SET kName = "Lunatique" WHERE ID = 1726;
UPDATE mob_db SET kName = "Sauvageon" WHERE ID = 1727;
UPDATE mob_db SET kName = "Jeune Loup du Désert" WHERE ID = 1728;
UPDATE mob_db SET kName = "Baphomet Jr." WHERE ID = 1729;
UPDATE mob_db SET kName = "Deviruchi" WHERE ID = 1730;
UPDATE mob_db SET kName = "Doppelganger" WHERE ID = 1731;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1732;
UPDATE mob_db SET kName = "Kiehl" WHERE ID = 1733;
UPDATE mob_db SET kName = "Kiehl D-01" WHERE ID = 1734;
UPDATE mob_db SET kName = "Alicel" WHERE ID = 1735;
UPDATE mob_db SET kName = "Aliot" WHERE ID = 1736;
UPDATE mob_db SET kName = "Aliza" WHERE ID = 1737;
UPDATE mob_db SET kName = "Constant" WHERE ID = 1738;
UPDATE mob_db SET kName = "Alicel" WHERE ID = 1739;
UPDATE mob_db SET kName = "Aliot" WHERE ID = 1740;
UPDATE mob_db SET kName = "Cookie de Noël" WHERE ID = 1741;
UPDATE mob_db SET kName = "Carat" WHERE ID = 1742;
UPDATE mob_db SET kName = "Cadeau Surprise" WHERE ID = 1743;
UPDATE mob_db SET kName = "Bruterose" WHERE ID = 1744;
UPDATE mob_db SET kName = "Constant" WHERE ID = 1745;
UPDATE mob_db SET kName = "Aliza" WHERE ID = 1746;
UPDATE mob_db SET kName = "Boa" WHERE ID = 1747;
UPDATE mob_db SET kName = "Anaconda" WHERE ID = 1748;
UPDATE mob_db SET kName = "Méduse" WHERE ID = 1749;
UPDATE mob_db SET kName = "Plante Rouge" WHERE ID = 1750;
UPDATE mob_db SET kName = "Valkyrie Randgris" WHERE ID = 1751;
UPDATE mob_db SET kName = "Skogul" WHERE ID = 1752;
UPDATE mob_db SET kName = "Frus" WHERE ID = 1753;
UPDATE mob_db SET kName = "Skeggiold" WHERE ID = 1754;
UPDATE mob_db SET kName = "Skeggiold" WHERE ID = 1755;
UPDATE mob_db SET kName = "Hydro" WHERE ID = 1756;
UPDATE mob_db SET kName = "Acidus" WHERE ID = 1757;
UPDATE mob_db SET kName = "Férus" WHERE ID = 1758;
UPDATE mob_db SET kName = "Acidus" WHERE ID = 1759;
UPDATE mob_db SET kName = "Férus" WHERE ID = 1760;
UPDATE mob_db SET kName = "Skogul" WHERE ID = 1761;
UPDATE mob_db SET kName = "Frus" WHERE ID = 1762;
UPDATE mob_db SET kName = "Skeggiold" WHERE ID = 1763;
UPDATE mob_db SET kName = "Skeggiold" WHERE ID = 1764;
UPDATE mob_db SET kName = "Valkyrie" WHERE ID = 1765;
UPDATE mob_db SET kName = "Angéling" WHERE ID = 1766;
UPDATE mob_db SET kName = "Déviling" WHERE ID = 1767;
UPDATE mob_db SET kName = "L'Ombre dans la Nuit" WHERE ID = 1768;
UPDATE mob_db SET kName = "Agav" WHERE ID = 1769;
UPDATE mob_db SET kName = "Echio" WHERE ID = 1770;
UPDATE mob_db SET kName = "Vanberk" WHERE ID = 1771;
UPDATE mob_db SET kName = "Isilla" WHERE ID = 1772;
UPDATE mob_db SET kName = "Hodremlin" WHERE ID = 1773;
UPDATE mob_db SET kName = "Témoin" WHERE ID = 1774;
UPDATE mob_db SET kName = "Neigeux" WHERE ID = 1775;
UPDATE mob_db SET kName = "Siroma" WHERE ID = 1776;
UPDATE mob_db SET kName = "Titan de Glace" WHERE ID = 1777;
UPDATE mob_db SET kName = "Gazeti" WHERE ID = 1778;
UPDATE mob_db SET kName = "Ktullanux" WHERE ID = 1779;
UPDATE mob_db SET kName = "Muscipular" WHERE ID = 1780;
UPDATE mob_db SET kName = "Drosera" WHERE ID = 1781;
UPDATE mob_db SET kName = "Roween" WHERE ID = 1782;
UPDATE mob_db SET kName = "Galion" WHERE ID = 1783;
UPDATE mob_db SET kName = "Stapo" WHERE ID = 1784;
UPDATE mob_db SET kName = "Atroce" WHERE ID = 1785;
UPDATE mob_db SET kName = "Agav" WHERE ID = 1786;
UPDATE mob_db SET kName = "Echio" WHERE ID = 1787;
UPDATE mob_db SET kName = "Titan de Glace" WHERE ID = 1788;
UPDATE mob_db SET kName = "Stalactite de Glace" WHERE ID = 1789;
UPDATE mob_db SET kName = "Rafflesia" WHERE ID = 1790;
UPDATE mob_db SET kName = "Galion" WHERE ID = 1791;
UPDATE mob_db SET kName = "Balon de Foot" WHERE ID = 1792;
UPDATE mob_db SET kName = "Mégalite" WHERE ID = 1793;
UPDATE mob_db SET kName = "Roween" WHERE ID = 1794;
UPDATE mob_db SET kName = "Chevalier Sanguinaire" WHERE ID = 1795;
UPDATE mob_db SET kName = "Aunoe" WHERE ID = 1796;
UPDATE mob_db SET kName = "Fanat" WHERE ID = 1797;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1798;
UPDATE mob_db SET kName = "Chevalier Seyren" WHERE ID = 1799;
UPDATE mob_db SET kName = "Assassin Cross Eremes" WHERE ID = 1800;
UPDATE mob_db SET kName = "Maître Forgeron Howard" WHERE ID = 1801;
UPDATE mob_db SET kName = "Prêtresse Margaretha" WHERE ID = 1802;
UPDATE mob_db SET kName = "Tireur d'Élite Cecil" WHERE ID = 1803;
UPDATE mob_db SET kName = "Sorcière Kathryne" WHERE ID = 1804;
UPDATE mob_db SET kName = "Chevalier Seyren" WHERE ID = 1805;
UPDATE mob_db SET kName = "Assassin Cross Eremes" WHERE ID = 1806;
UPDATE mob_db SET kName = "Maître Forgeron Howard" WHERE ID = 1807;
UPDATE mob_db SET kName = "Prêtresse Margaretha" WHERE ID = 1808;
UPDATE mob_db SET kName = "Tireur d'Élite Cecil" WHERE ID = 1809;
UPDATE mob_db SET kName = "Sorcière Kathryne" WHERE ID = 1810;
UPDATE mob_db SET kName = "Bandit" WHERE ID = 1811;
UPDATE mob_db SET kName = "Lude" WHERE ID = 1812;
UPDATE mob_db SET kName = "Hydro" WHERE ID = 1813;
UPDATE mob_db SET kName = "Fleur de Lune" WHERE ID = 1814;
UPDATE mob_db SET kName = "Gâteau de Riz" WHERE ID = 1815;
UPDATE mob_db SET kName = "Calebasse" WHERE ID = 1816;
UPDATE mob_db SET kName = "Détale" WHERE ID = 1817;
UPDATE mob_db SET kName = "Toquant" WHERE ID = 1818;
UPDATE mob_db SET kName = "Bathory" WHERE ID = 1819;
UPDATE mob_db SET kName = "Yéti" WHERE ID = 1820;
UPDATE mob_db SET kName = "Loup du Désert" WHERE ID = 1821;
UPDATE mob_db SET kName = "Deviruchi" WHERE ID = 1822;
UPDATE mob_db SET kName = "Cœur-de-Glace" WHERE ID = 1823;
UPDATE mob_db SET kName = "Jeune Garm" WHERE ID = 1824;
UPDATE mob_db SET kName = "Gobelin de Noël" WHERE ID = 1825;
UPDATE mob_db SET kName = "Brume" WHERE ID = 1826;
UPDATE mob_db SET kName = "Sasquatch" WHERE ID = 1827;
UPDATE mob_db SET kName = "Gullinbrusti" WHERE ID = 1828;
UPDATE mob_db SET kName = "Maître des Épées" WHERE ID = 1829;
UPDATE mob_db SET kName = "Maître des Arcs" WHERE ID = 1830;
UPDATE mob_db SET kName = "Salamandre" WHERE ID = 1831;
UPDATE mob_db SET kName = "Ifrit" WHERE ID = 1832;
UPDATE mob_db SET kName = "Kasa" WHERE ID = 1833;
UPDATE mob_db SET kName = "Salamandre" WHERE ID = 1834;
UPDATE mob_db SET kName = "Kasa" WHERE ID = 1835;
UPDATE mob_db SET kName = "Magmaring" WHERE ID = 1836;
UPDATE mob_db SET kName = "Esprit du Feu" WHERE ID = 1837;
UPDATE mob_db SET kName = "Cogneur" WHERE ID = 1838;
UPDATE mob_db SET kName = "Byorgue" WHERE ID = 1839;
UPDATE mob_db SET kName = "Sauvage Doré" WHERE ID = 1840;
UPDATE mob_db SET kName = "Minion du Grand Serpent" WHERE ID = 1841;
UPDATE mob_db SET kName = "Minion du Grand Serpent" WHERE ID = 1842;
UPDATE mob_db SET kName = "Minion du Grand Serpent" WHERE ID = 1843;
UPDATE mob_db SET kName = "Minion du Grand Serpent" WHERE ID = 1844;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1845;
UPDATE mob_db SET kName = "Pierre des Rêves" WHERE ID = 1846;
UPDATE mob_db SET kName = "Poring" WHERE ID = 1847;
UPDATE mob_db SET kName = "Baphomet" WHERE ID = 1848;
UPDATE mob_db SET kName = "Osiris" WHERE ID = 1849;
UPDATE mob_db SET kName = "Héros des Orcs" WHERE ID = 1850;
UPDATE mob_db SET kName = "Mobster" WHERE ID = 1851;
UPDATE mob_db SET kName = "Angéling" WHERE ID = 1852;
UPDATE mob_db SET kName = "Déviling" WHERE ID = 1853;
UPDATE mob_db SET kName = "Muka" WHERE ID = 1854;
UPDATE mob_db SET kName = "Spore Empoisonnée" WHERE ID = 1855;
UPDATE mob_db SET kName = "Magnolia" WHERE ID = 1856;
UPDATE mob_db SET kName = "Marin" WHERE ID = 1857;
UPDATE mob_db SET kName = "Plancton" WHERE ID = 1858;
UPDATE mob_db SET kName = "Mandragore" WHERE ID = 1859;
UPDATE mob_db SET kName = "Coco" WHERE ID = 1860;
UPDATE mob_db SET kName = "Choco" WHERE ID = 1861;
UPDATE mob_db SET kName = "Martin" WHERE ID = 1862;
UPDATE mob_db SET kName = "Lapin Bondissant" WHERE ID = 1863;
UPDATE mob_db SET kName = "Cadavéreux" WHERE ID = 1864;
UPDATE mob_db SET kName = "Zombie en Haillons" WHERE ID = 1865;
UPDATE mob_db SET kName = "Dogue des Enfers" WHERE ID = 1866;
UPDATE mob_db SET kName = "Banshee" WHERE ID = 1867;
UPDATE mob_db SET kName = "Banshee" WHERE ID = 1868;
UPDATE mob_db SET kName = "Crâne Ardent" WHERE ID = 1869;
UPDATE mob_db SET kName = "Nécromancien" WHERE ID = 1870;
UPDATE mob_db SET kName = "Évêque Déchu Hibram" WHERE ID = 1871;
UPDATE mob_db SET kName = "Mouche des Enfers" WHERE ID = 1872;
UPDATE mob_db SET kName = "Beelzébub" WHERE ID = 1873;
UPDATE mob_db SET kName = "Beelzébub" WHERE ID = 1874;
UPDATE mob_db SET kName = "Tristan III" WHERE ID = 1875;
UPDATE mob_db SET kName = "Seigneur de la Mort" WHERE ID = 1876;
UPDATE mob_db SET kName = "Cristal" WHERE ID = 1877;
UPDATE mob_db SET kName = "Plante Luminescente" WHERE ID = 1878;
UPDATE mob_db SET kName = "Éclipse" WHERE ID = 1879;
UPDATE mob_db SET kName = "Gobelin des Bois" WHERE ID = 1880;
UPDATE mob_db SET kName = "Les" WHERE ID = 1881;
UPDATE mob_db SET kName = "Baba Yaga" WHERE ID = 1882;
UPDATE mob_db SET kName = "Uzhas" WHERE ID = 1883;
UPDATE mob_db SET kName = "Mavka" WHERE ID = 1884;
UPDATE mob_db SET kName = "Zmei Gorinich" WHERE ID = 1885;
UPDATE mob_db SET kName = "Mavka" WHERE ID = 1886;
UPDATE mob_db SET kName = "Cœur-de-Glace" WHERE ID = 1887;
UPDATE mob_db SET kName = "Jeune Garm" WHERE ID = 1888;
UPDATE mob_db SET kName = "Garde de Marozka" WHERE ID = 1889;
UPDATE mob_db SET kName = "Koshei L'Immortel" WHERE ID = 1890;
UPDATE mob_db SET kName = "Valkyrie" WHERE ID = 1891;
UPDATE mob_db SET kName = "Loli Ruri" WHERE ID = 1892;
UPDATE mob_db SET kName = "Chevalier des Abysses" WHERE ID = 1893;
UPDATE mob_db SET kName = "Pouring" WHERE ID = 1894;
UPDATE mob_db SET kName = "Seyren Windsor" WHERE ID = 1895;
UPDATE mob_db SET kName = "Kathryne Keyron" WHERE ID = 1896;
UPDATE mob_db SET kName = "Baphomet" WHERE ID = 1897;
UPDATE mob_db SET kName = "Zombie" WHERE ID = 1898;
UPDATE mob_db SET kName = "Maître des Épées" WHERE ID = 1899;
UPDATE mob_db SET kName = "Condor" WHERE ID = 1901;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1902;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1903;
UPDATE mob_db SET kName = "Bombe Poring" WHERE ID = 1904;
UPDATE mob_db SET kName = "Barricade" WHERE ID = 1905;
UPDATE mob_db SET kName = "Barricade" WHERE ID = 1906;
UPDATE mob_db SET kName = "Pierre Gardienne" WHERE ID = 1907;
UPDATE mob_db SET kName = "Pierre Gardienne" WHERE ID = 1908;
UPDATE mob_db SET kName = "Dépôt de Nourriture" WHERE ID = 1909;
UPDATE mob_db SET kName = "Dépôt de Nourriture" WHERE ID = 1910;
UPDATE mob_db SET kName = "Drapeau Neutre" WHERE ID = 1911;
UPDATE mob_db SET kName = "Drapeau du Lion" WHERE ID = 1912;
UPDATE mob_db SET kName = "Drapeau de l'Aigle" WHERE ID = 1913;
UPDATE mob_db SET kName = "Cristal Bleu" WHERE ID = 1914;
UPDATE mob_db SET kName = "Cristal Rose" WHERE ID = 1915;
UPDATE mob_db SET kName = "Satan Morroc" WHERE ID = 1916;
UPDATE mob_db SET kName = "Morroc Blessé" WHERE ID = 1917;
UPDATE mob_db SET kName = "Ombre de Morroc" WHERE ID = 1918;
UPDATE mob_db SET kName = "Ombre de Morroc" WHERE ID = 1919;
UPDATE mob_db SET kName = "Ombre de Morroc" WHERE ID = 1920;
UPDATE mob_db SET kName = "Ombre de Morroc" WHERE ID = 1921;
UPDATE mob_db SET kName = "Ombre de Morroc" WHERE ID = 1922;
UPDATE mob_db SET kName = "Ombre de Morroc" WHERE ID = 1923;
UPDATE mob_db SET kName = "Ombre de Morroc" WHERE ID = 1924;
UPDATE mob_db SET kName = "Ombre de Morroc" WHERE ID = 1925;
UPDATE mob_db SET kName = "Jack" WHERE ID = 1926;
UPDATE mob_db SET kName = "Murmure" WHERE ID = 1927;
UPDATE mob_db SET kName = "Deviruchi" WHERE ID = 1928;
UPDATE mob_db SET kName = "Grand Démon Baphomet" WHERE ID = 1929;
UPDATE mob_db SET kName = "Piamette" WHERE ID = 1930;
UPDATE mob_db SET kName = "Dame des Souhaits" WHERE ID = 1931;
UPDATE mob_db SET kName = "Gardien du Jardin" WHERE ID = 1932;
UPDATE mob_db SET kName = "Guetteur du Jardin" WHERE ID = 1933;
UPDATE mob_db SET kName = "Fleur Bleue" WHERE ID = 1934;
UPDATE mob_db SET kName = "Fleur Rouge" WHERE ID = 1935;
UPDATE mob_db SET kName = "Fleur Jaune" WHERE ID = 1936;
UPDATE mob_db SET kName = "Constant" WHERE ID = 1937;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1938;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1939;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1940;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1941;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1942;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1943;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1944;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1945;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1946;
UPDATE mob_db SET kName = "Piamette" WHERE ID = 1947;
UPDATE mob_db SET kName = "Egnigem Cenia" WHERE ID = 1948;
UPDATE mob_db SET kName = "Garde du Camp" WHERE ID = 1949;
UPDATE mob_db SET kName = "Garde du Camp" WHERE ID = 1950;
UPDATE mob_db SET kName = "Cristal" WHERE ID = 1951;
UPDATE mob_db SET kName = "Cristal" WHERE ID = 1952;
UPDATE mob_db SET kName = "Cristal" WHERE ID = 1953;
UPDATE mob_db SET kName = "Cristal" WHERE ID = 1954;
UPDATE mob_db SET kName = "Coffre" WHERE ID = 1955;
UPDATE mob_db SET kName = "Naght Sieger" WHERE ID = 1956;
UPDATE mob_db SET kName = "Entweihen Crothen" WHERE ID = 1957;
UPDATE mob_db SET kName = "Esquille" WHERE ID = 1958;
UPDATE mob_db SET kName = "Esquille de Guérison" WHERE ID = 1959;
UPDATE mob_db SET kName = "Esquille de Magie" WHERE ID = 1960;
UPDATE mob_db SET kName = "Esquille de Purification" WHERE ID = 1961;
UPDATE mob_db SET kName = "Voleur de noël" WHERE ID = 1962;
UPDATE mob_db SET kName = "Poupée du Nouvel An" WHERE ID = 1963;
UPDATE mob_db SET kName = "Cauchemar" WHERE ID = 1964;
UPDATE mob_db SET kName = "Bruterose" WHERE ID = 1965;
UPDATE mob_db SET kName = "Doppelganger" WHERE ID = 1966;
UPDATE mob_db SET kName = "Egnigem Cenia" WHERE ID = 1967;
UPDATE mob_db SET kName = "Strouf" WHERE ID = 1968;
UPDATE mob_db SET kName = "Marc" WHERE ID = 1969;
UPDATE mob_db SET kName = "Obeune" WHERE ID = 1970;
UPDATE mob_db SET kName = "Vadon" WHERE ID = 1971;
UPDATE mob_db SET kName = "Marina" WHERE ID = 1972;
UPDATE mob_db SET kName = "Poring" WHERE ID = 1973;
UPDATE mob_db SET kName = "Maître Banshee" WHERE ID = 1974;
UPDATE mob_db SET kName = "Maître Scruteur" WHERE ID = 1975;
UPDATE mob_db SET kName = "Cobalt" WHERE ID = 1976;
UPDATE mob_db SET kName = "Métaling Renforcé" WHERE ID = 1977;
UPDATE mob_db SET kName = "Apocalypse des Enfers" WHERE ID = 1978;
UPDATE mob_db SET kName = "Zukadam" WHERE ID = 1979;
UPDATE mob_db SET kName = "Kubkin" WHERE ID = 1980;
UPDATE mob_db SET kName = "Garde en Chef" WHERE ID = 1981;
UPDATE mob_db SET kName = "Orc Tirreur d'Élite" WHERE ID = 1982;
UPDATE mob_db SET kName = "Esprit Dérangé d'Orc" WHERE ID = 1983;
UPDATE mob_db SET kName = "Chamane Cargalache" WHERE ID = 1984;
UPDATE mob_db SET kName = "Dandelion" WHERE ID = 1985;
UPDATE mob_db SET kName = "Tatacho" WHERE ID = 1986;
UPDATE mob_db SET kName = "Centipède" WHERE ID = 1987;
UPDATE mob_db SET kName = "Népenthès" WHERE ID = 1988;
UPDATE mob_db SET kName = "Lion des Collines" WHERE ID = 1989;
UPDATE mob_db SET kName = "Mammouth Rochedure" WHERE ID = 1990;
UPDATE mob_db SET kName = "Tendrillion" WHERE ID = 1991;
UPDATE mob_db SET kName = "Cornus" WHERE ID = 1992;
UPDATE mob_db SET kName = "Naga" WHERE ID = 1993;
UPDATE mob_db SET kName = "Luciola Vespa" WHERE ID = 1994;
UPDATE mob_db SET kName = "Pinguicula" WHERE ID = 1995;
UPDATE mob_db SET kName = "Bacsojin" WHERE ID = 1996;
UPDATE mob_db SET kName = "Tatacho" WHERE ID = 1997;
UPDATE mob_db SET kName = "Lion des Collines" WHERE ID = 1998;
UPDATE mob_db SET kName = "Larve de Centipède" WHERE ID = 1999;
