UPDATE mob_db SET kName = "Plante Luminescente" WHERE ID = 1083;
UPDATE mob_db SET kName = "Chevalier Sanguinaire" WHERE ID = 1268;
UPDATE mob_db SET kName = "Cœur-de-Glace" WHERE ID = 1319;
UPDATE mob_db SET kName = "Poissonard" WHERE ID = 1451;
UPDATE mob_db SET kName = "Chimère" WHERE ID = 1456;
UPDATE mob_db SET kName = "Exécuteur" WHERE ID = 1487;
UPDATE mob_db SET kName = "Hylozoïste" WHERE ID = 1510;
UPDATE mob_db SET kName = "Gangster" WHERE ID = 1592;
UPDATE mob_db SET kName = "Cœur-de-Glace" WHERE ID = 1594;
UPDATE mob_db SET kName = "Boa" WHERE ID = 1747;
UPDATE mob_db SET kName = "Méduse" WHERE ID = 1749;
UPDATE mob_db SET kName = "Cœur-de-Glace" WHERE ID = 1823;
UPDATE mob_db SET kName = "Plante Luminescente" WHERE ID = 1878;
UPDATE mob_db SET kName = "Cœur-de-Glace" WHERE ID = 1887;
UPDATE mob_db SET kName = "Dogue des Enfers" WHERE ID = 1866;
UPDATE mob_db SET kName = "Cristal Rose" WHERE ID = 1915;
UPDATE mob_db SET kName = "Cristal Bleu" WHERE ID = 1914;